spring:
  application:
    name: stockr

  datasource:
    driver-class-name: org.postgresql.Driver
    username: lunov
    url: jdbc:postgresql://localhost:5432/lunov
  jpa:
    hibernate:
      ddl-auto: validate


  flyway:
    locations: classpath:db/migration